### PR TITLE
Pause Menu, Quit Game Button, Audio Manager

### PR DESCRIPTION
**Pull request by glowiingo**
- ESC to open pause menu and freeze game 
- Sliders for Volume
- Settings Menu button to toggle pause menu
- Quit Game Button (only works during build) 
- Audio Manager object and script

### CODE REVIEW

**Comment by glowiingo** [comment]
Currently continuing to update the audio manager! :)

**Comment by glowiingo** [comment]
Need to script masking for the health bar in the UI to display health values

**Comment by glowiingo** [comment]
Side note: Just discovered you can use sprite mask for the health bar so it needs to be updated

**Comment by glowiingo** [comment]
PSS. I dug a little into the sprites and it might not be as good an idea as i thought maybe i just stick to ui masking LOL

**Review by Charles-Huang-Y4 — APPROVED** [review]
lgtm

**Pull request merged**
